runtime:
  cache_dir: ./.cache/antora

site:
  title: Modern Application Development Roadshow - Dev Track
  start_page: modules::1-introduction.adoc

content:
  sources:
    - url: .
      branches: main
      start_path: content

ui:
  bundle:
    url: https://github.com/danieloh30/course-ui/raw/main/ui-bundle-fix-rexp.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"

output:
  dir: ./gh-pages
